
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 27 10:44:42 GMT-03:00 2012
//----------------------------------------------------

package com.analisador.sintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 31;
  public static final int CHAR = 6;
  public static final int MAIORIG = 38;
  public static final int SOMA = 28;
  public static final int MENORQ = 36;
  public static final int NUMHEXA = 21;
  public static final int MAIORQ = 35;
  public static final int INT = 5;
  public static final int E = 34;
  public static final int IGUAL = 25;
  public static final int OU = 33;
  public static final int VIRG = 11;
  public static final int APAR = 9;
  public static final int ACOL = 13;
  public static final int FCOL = 14;
  public static final int DIV = 26;
  public static final int FPAR = 10;
  public static final int IF = 15;
  public static final int ID = 24;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int VOID = 19;
  public static final int PTVIRG = 2;
  public static final int UNSUB = 30;
  public static final int ELSE = 16;
  public static final int ACHA = 3;
  public static final int WHILE = 17;
  public static final int FCHA = 4;
  public static final int FLOAT = 7;
  public static final int MENORIG = 37;
  public static final int NUMINT = 20;
  public static final int NUMFLOAT = 22;
  public static final int STRING = 23;
  public static final int PSEUDO_ELSE = 12;
  public static final int ATRIBUI = 27;
  public static final int NAO = 32;
  public static final int SUB = 29;
}

