/*
 * Generated by classgen, version 1.5
 * 14/05/12 18:33
 */
package com.analisador.no;

public abstract class Exp {

  private int resultadoCalculado;
  private boolean reultadoAvaliado;
  public int getValor() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setValor(int valor) {
    throw new ClassCastException("tried to call abstract method");
  }

  public Exp getExp_esq() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setExp_esq(Exp exp_esq) {
    throw new ClassCastException("tried to call abstract method");
  }

  public int getOperador() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setOperador(int operador) {
    throw new ClassCastException("tried to call abstract method");
  }

  public Exp getExp_dir() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setExp_dir(Exp exp_dir) {
    throw new ClassCastException("tried to call abstract method");
  }

  public int getResultadoCalculado() {
    return resultadoCalculado;
  }

  public void setResultadoCalculado(int resultadoCalculado) {
    this.resultadoCalculado = resultadoCalculado;
  }

  public boolean getReultadoAvaliado() {
    return reultadoAvaliado;
  }

  public void setReultadoAvaliado(boolean reultadoAvaliado) {
    this.reultadoAvaliado = reultadoAvaliado;
  }

  public String toString() {
    return toString("");
  }

  public abstract String toString(String tab);
}
