/*
 * Generated by classgen, version 1.5
 * 14/05/12 18:33
 */
package com.analisador.no;

public class Inteiro extends Exp {

  private int valor;

  public Inteiro (int valor) {
    this.valor = valor;
  }

  public int getValor() {
    return valor;
  }

  public void setValor(int valor) {
    this.valor = valor;
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Inteiro(\n");
    buffer.append("  "+tab+valor);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Inteiro]");
    return buffer.toString();
  }
}
