/*
 * Generated by classgen, version 1.5
 * 13/05/12 14:27
 */
package no;

public interface Operador {

  public final static int SOMA = 0;
  public final static int MULT = 1;
  public final static int SUB = 2;
  public final static int DIV = 3;
  public final static int IGUAL = 4;
  public final static int MENORIG = 5;
  public final static int MAIORIG = 6;
  public final static int MENORQ = 7;
  public final static int MAIORQ = 8;

}
