/*
 * Generated by classgen, version 1.5
 * 13/05/12 16:04
 */
package com.anaisador.no;

public abstract class Exp {

  public int getValor() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setValor(int valor) {
    throw new ClassCastException("tried to call abstract method");
  }

  public Exp getExp_esq() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setExp_esq(Exp exp_esq) {
    throw new ClassCastException("tried to call abstract method");
  }

  public int getOperador() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setOperador(int operador) {
    throw new ClassCastException("tried to call abstract method");
  }

  public Exp getExp_dir() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setExp_dir(Exp exp_dir) {
    throw new ClassCastException("tried to call abstract method");
  }

  public String toString() {
    return toString("");
  }

  public abstract String toString(String tab);
}
