/*
 * Generated by classgen, version 1.5
 * 14/05/12 18:33
 */
package com.analisador.ast.no;

import com.analisador.semantico.Visitor;

public class ExpInt extends Exp {

  private int valorI;

  public ExpInt (int valor) {
    this.valorI = valor;
  }

  public int getValorI() {
    return valorI;
  }

  public void setValor(int valor) {
    this.valorI = valor;
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Inteiro(\n");
    buffer.append("  "+tab+valorI);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Inteiro]");
    return buffer.toString();
  }
  
  public void accept(Visitor v)throws Exception {
		v.visit(this);
	}
}
