/*
 * Generated by classgen, version 1.5
 * 14/05/12 18:33
 */
package com.analisador.ast.no;

import com.analisador.semantico.Visitor;

public class ExpressaoBinaria extends Exp {

  private Exp exp_esq;
  private String operador;
  private Exp exp_dir;

  public ExpressaoBinaria (Exp exp_esq, String operador, Exp exp_dir) {
    this.exp_esq = exp_esq;
    this.operador = operador;
    this.exp_dir = exp_dir;
  }
  
  public void accept(Visitor v) throws Exception {
		v.visit(this);
	}

  public Exp getExp_esq() {
    return exp_esq;
  }

  public void setExp_esq(Exp exp_esq) {
    this.exp_esq = exp_esq;
  }



public void setOperador(String operador) {
    this.operador = operador;
  }

public String getOperadorString() {
	return operador;
}

  public Exp getExp_dir() {
    return exp_dir;
  }

  public void setExp_dir(Exp exp_dir) {
    this.exp_dir = exp_dir;
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("ExpressaoBinaria(\n");
      if (exp_esq != null)
        buffer.append(exp_esq.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append("  "+tab+operador);
    buffer.append("\n");
      if (exp_dir != null)
        buffer.append(exp_dir.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [ExpressaoBinaria]");
    return buffer.toString();
  }
}
